development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: our_uninot
  pool: 5
  username: root
  password: Gkkkdro74hKhs22
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: our_uninot
  pool: 5
  username: root
  password: Gkkkdro74hKhs22
  socket: /var/run/mysqld/mysqld.sock
